---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openweathermap-api-key
  namespace: default
spec:
  encryptedData:
    openweathermap-api-key: AgBm3myqlnLC3peWUOG9/vl5zzqwzTvyOXXAp54XQ9S3iQjC7GO+Bo5an9KVRqWQVQ9JY8DjGAp/7CYrKdgplOLG63bBGVTS1QdmH72xYSbEF0Je9pJwZ8+dD9q/rhoZzTgUqSvF/CFCtBI9dr2aE25jmxGc9TV/VnzhscX12o/6+kxz9p5hEhZ7QTHbdWEaVjjbo4YQ1aXyb0XD9Z/xxG3Hwf3N97sE9z39IvoF/aAGEKrCGMZYtI0T0fuUwCqji8JgjJ9SguPq4GzRRpUeJGnB+LSZFB95k1lAj6yhUP95DIwUGRon7ksQ/AXcJMFrsaQQ7kcxwUuTlbvoc7Vc84SQi6ZPv0yDypyr6pUE+8MrzvTzchXgsofCUC7FWDIqzH5bGc3CJ1OEP21FxW87NtvTr9xgap5/bOqLYs9U8wv02bL1yqVGLfWBoy+QLIY5viVUgj+kVzLftQlkimSMbfNNUtCJjpYYrLNoknU+fyGqsQnksXQSFlfwJZTOKFIcXwQ+exAkja8KpBYzehJulvU8A1UZZ0ylqniLTgxEMpOJ7Vu1MsBuBddZn4qHModbM1dCRC6GJEVQAaFYrZWonb9nhqLX9xei2LE2j/amaw6D7oZQ0b0+4cMsGC/mtRMgWMC5VorQH8qRPXtSitztOQv1mejvnpJWv0mUvmWiNsynaALMbA89OorMNPc5xn5HogTpygp69lb03n7UGwBBIvkQHGD336Uwh07L4iZ5lOe4sA==
  template:
    metadata:
      creationTimestamp: null
      name: openweathermap-api-key
      namespace: default
