apiVersion: v1
kind: Service
metadata:
  name: datasette
spec:
  type: NodePort
  selector:
    app: datasette
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30080 # NodePort range is 30000-32767
